name: mightyweb
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #BASE
  nb_utils: ^7.1.6
  google_fonts: ^6.2.1

  #UI
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1
  package_info_plus: ^8.3.0
  flutter_speed_dial: ^7.0.0
  flutter_native_splash: ^2.4.6

  #STATE MANAGEMENT
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

  #STORAGE & PERMISSION
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  provider: ^6.1.5

  #CONNECTIVITY
  http: ^1.4.0
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  store_redirect: ^2.0.4

  #Firebase
  firebase_in_app_messaging: ^0.8.1+9
  firebase_messaging: ^15.2.9
  firebase_core: ^3.15.1

  # PUSH NOTIFICATION
  onesignal_flutter: ^5.3.4

  # ADS
  google_mobile_ads: ^6.0.0
  facebook_audience_network: ^1.0.1

  # WEB TOOLS
  flutter_inappwebview: ^6.1.5

  qr_code_scanner: ^1.0.1

  flutter_localizations:
    sdk: flutter
  rename_app: ^1.6.5
  flutter_launcher_icons: ^0.14.4
  advanced_in_app_review: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  mobx_codegen: ^2.7.1
  change_app_package_name: ^1.5.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  js: ^0.6.3
  http: ^1.2.1
  web: ^0.5.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#ffffff"   # white background
  color_dark: "#000000" # dark mode background
  android_12:
    color: "#ffffff"
    color_dark: "#000000"
  android: true
  ios: true
  web: false


flutter:
  uses-material-design: true
  assets:
    - assets/
    - lang/
