// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwNbLKyrjuf5pHDfw2hsgcm30LJyUV7dM',
    appId: '1:233592377546:web:5b25eb952435f311952433',
    messagingSenderId: '233592377546',
    projectId: 'egar-students',
    authDomain: 'egar-students.firebaseapp.com',
    storageBucket: 'egar-students.firebasestorage.app',
    measurementId: 'G-Q8TCFQQY7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQqFp5CgTvmw5VKVW35X0va_MqDCYhnW4',
    appId: '1:233592377546:android:648cbd51248a317b952433',
    messagingSenderId: '233592377546',
    projectId: 'egar-students',
    storageBucket: 'egar-students.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvaF-jF7BuDlEqpjDiFKkAR_FQaKBqkrw',
    appId: '1:233592377546:ios:ec994cb5e48c4aca952433',
    messagingSenderId: '233592377546',
    projectId: 'egar-students',
    storageBucket: 'egar-students.firebasestorage.app',
    iosBundleId: 'com.egar.students',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvaF-jF7BuDlEqpjDiFKkAR_FQaKBqkrw',
    appId: '1:233592377546:ios:8bcc8b20fc6f5355952433',
    messagingSenderId: '233592377546',
    projectId: 'egar-students',
    storageBucket: 'egar-students.firebasestorage.app',
    iosBundleId: 'com.egar.studentslyFlutter',
  );
}
